### PR TITLE
Add \long to definition to mitigate issue.

### LINKED ISSUE #2: Error parser raises unexpected error when error line is empty
Example document:
```tex
\documentclass{article}
\usepackage{asypictureB}
\begin{document}
\begin{asypicture}{name=foo}
  label("a);
\end{asypicture}
\end{document}
```

Content of `a-foo_errors.txt`:
```

^
a-foo.asy: 6.1: string not terminated

error: could not load module 'a-foo.asy'
```

Resulting TeX error:
```
Runaway argument?
! Paragraph ended before \@asy@processerrorline was complete.
<to be read again> 
                   \par 
l.6 \end{asypicture}                
```
Expected behavior: that `asypictureB` cleanly wraps the Asymptote error.

### PR DESCRIPTION
**Pull request by charlesstaats**
The linked issue can be mitigated by making `\@asy@processerrorline` into a `\long` macro (so it can consume line boundaries (i.e., `\par` tokens) in its arguments). This likely doesn't address the underlying issue (whatever that may be), but it should at least make the package usable in this case.

### CODE REVIEW

**Comment by user202729** [comment]
I think (one of the) underlying issue is that there are 3 uses of `\read` instead of `\readline`. `\read` tokenizes the line under the current category regime, which includes two consecutive newlines being tokenized into `\par` --- it would be safer to use `\readline` instead, although admittedly that makes the programming a bit harder because you need to match the `asy` string in other cat instead of letter cat.

**Comment by charlesstaats** [comment]
I've changed one particular instance of the line `\endlinechar=‘ˆˆJ` to `\endlinechar=-1`. This has eliminated several gratuitous empty lines in the error message, and appears to make the `\long` declaration unnecessary. Let me know if it works for you.

I looked into `\read` versus `\readline`, and there's no clear consensus that `\readline` is better. To avoid the programming issues you mentioned, I've continued to use `\read`. If there are other reasons to prefer `\readline`, I'm happy to hear them. (If the implications are something like a minor misformatting of the error message, I'm still interested to know about it, but I reserve the right to deprioritize fixing it.)

**Comment by user202729** [comment]
Tokenizing all these tokens as TeX tokens has the obvious implications.

Example 1.

```tex
%! TEX program = pdflatex
\documentclass{article}
\usepackage{asypictureB}
\begin{document}
\begin{asypicture}{}
    unitsize(1cm);
    draw((0, 0)--(1, 1));
    var      ""     error;
\end{asypicture}
\end{document}
```

⟹

```
! Package asypictureB Error: 
var "" error;
^
a-noname.asy: 7.15: syntax error
error: could not load module 'a-noname.asy'

3 
4 
5     unitsize(1cm);
6     draw((0, 0)--(1, 1));
7     var      ""     error;
.
```

Problem:

```
! Package asypictureB Error: 
var "" error;
^
```

the multiple spaces are collapsed into one.

2.

```
%! TEX program = pdflatex
\documentclass{article}
\usepackage{asypictureB}
\begin{document}
\begin{asypicture}{}
    unitsize(1cm);
    draw((0, 0)--(1, 1));
    {
\end{asypicture}
\end{document}
```

Error:

```
Runaway definition?
->{ 
! File ended within \read.
<read 4> 
         
l.9 \end{asypicture}
                    
? 
```

3.

```
%! TEX program = pdflatex
\documentclass{article}
\usepackage{asypictureB}
\begin{document}
\begin{asypicture}{}
    unitsize(1cm);
    draw((0, 0)--(1, 1));
    "\ab" error
\end{asypicture}
\end{document}
```

Error:

```

! Undefined control sequence.
\@asyerrormessage ->
"\ab 
                          " error
^
a-noname.asy: 7.11: syntax error
error: ...
l.9 \end{asypicture}
                    
```

Using `\readline` is safer.

**Comment by charlesstaats** [comment]
Those are some pretty good points. I've changed the two instances of `\read` for comparing files to `\readline`, which for some reason seems to fix your Example 2 (unmatched `{`). I consider Example 1 (collapsing whitespace) unfortunate but not critical since the only remaining use of `\read` is for parsing and printing the error message.

Example 3 (undefined control sequence) still seems to be a major bug. Unfortunately, it may be beyond my capability to fix. (The error-parsing code of asypictureB was the culmination of my TeX programming expertise, which has since grown rusty.)

**Comment by user202729** [comment]
I see, looks like you don't fully understand what's the difference either. (no offense intended) I'll try to fix it and send a pull request.

**Comment by charlesstaats** [comment]
> I see, looks like you don't fully understand what's the difference either. (no offense intended)

No offense taken. I mostly understand the difference between `\read` and `\readline`, but I had forgotten (to the extent I ever knew) about tools like `\noexpand` and especially `\detokenize` that make your modifications feasible. Thanks!

**Pull request merged**
